/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */


/**
 * Event raised by a {@link module:platedetector.PlateDetectorFilter 
 * PlateDetectorFilter} when a plate is found in the data streamed.
 *
 * @event module:platedetector#PlateDetected
 *
 * @type {module:platedetector#event:Media}
 *
 * @property {external:String} plate
 *  Plate identification that was detected by the filter
 */
